package ru.terra.activitystore.db.entity;
// Generated 09.07.2012 18:44:53 by Hibernate Tools 3.2.1.GA


import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Block generated by hbm2java
 */
@Entity
@Table(name="block"
    ,catalog="activitystore"
)
public class Block  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Integer parent;
     private Date creationDate;
     private Date updateDate;

    public Block() {
    }

	
    public Block(String name, Integer parent, Date creationDate) {
        this.name = name;
        this.parent = parent;
        this.creationDate = creationDate;
    }
    public Block(String name, int parent, Date creationDate, Date updateDate) {
       this.name = name;
       this.parent = parent;
       this.creationDate = creationDate;
       this.updateDate = updateDate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="name", nullable=false, length=200)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="parent", nullable=false)
    public Integer getParent() {
        return this.parent;
    }
    
    public void setParent(Integer parent) {
        this.parent = parent;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="creation_date", nullable=false, length=19)
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="update_date", length=19)
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }




}


