package ru.terra.activitystore.db.entity;
// Generated 09.07.2012 18:44:53 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ListVal generated by hbm2java
 */
@Entity
@Table(name="list_val"
    ,catalog="activitystore"
)
public class ListVal  implements java.io.Serializable {


     private Integer valId;
     private Vlist vlist;
     private String value;

    public ListVal() {
    }

    public ListVal(Vlist vlist, String value) {
       this.vlist = vlist;
       this.value = value;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="val_id", unique=true, nullable=false)
    public Integer getValId() {
        return this.valId;
    }
    
    public void setValId(Integer valId) {
        this.valId = valId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="list_id", nullable=false)
    public Vlist getVlist() {
        return this.vlist;
    }
    
    public void setVlist(Vlist vlist) {
        this.vlist = vlist;
    }
    
    @Column(name="value", nullable=false, length=500)
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }




}


