package ru.terra.activitystore.db.entity;
// Generated 09.07.2012 18:44:53 by Hibernate Tools 3.2.1.GA


import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Template generated by hbm2java
 */
@Entity
@Table(name="template"
    ,catalog="activitystore"
)
public class Template  implements java.io.Serializable {


     private Integer id;
     private Card card;
     private String name;
     private Date creationDate;
     private Date updateDate;

    public Template() {
    }

	
    public Template(Card card, String name, Date creationDate) {
        this.card = card;
        this.name = name;
        this.creationDate = creationDate;
    }
    public Template(Card card, String name, Date creationDate, Date updateDate) {
       this.card = card;
       this.name = name;
       this.creationDate = creationDate;
       this.updateDate = updateDate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="card", nullable=false)
    public Card getCard() {
        return this.card;
    }
    
    public void setCard(Card card) {
        this.card = card;
    }
    
    @Column(name="name", nullable=false, length=512)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="creation_date", nullable=false, length=19)
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="update_date", length=19)
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }




}


