package ru.terra.activitystore.db.entity;
// Generated 05.07.2012 13:20:05 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * BlockId generated by hbm2java
 */
@Embeddable
public class BlockId  implements java.io.Serializable {


     private int id;
     private int parent;

    public BlockId() {
    }

    public BlockId(int id, int parent) {
       this.id = id;
       this.parent = parent;
    }
   

    @Column(name="id", nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    @Column(name="parent", nullable=false)
    public int getParent() {
        return this.parent;
    }
    
    public void setParent(int parent) {
        this.parent = parent;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof BlockId) ) return false;
		 BlockId castOther = ( BlockId ) other; 
         
		 return (this.getId()==castOther.getId())
 && (this.getParent()==castOther.getParent());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getId();
         result = 37 * result + this.getParent();
         return result;
   }   


}


