package ru.terra.activitystore.db.entity;
// Generated 05.07.2012 13:20:05 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CellId generated by hbm2java
 */
@Embeddable
public class CellId  implements java.io.Serializable {


     private int id;
     private int cardId;

    public CellId() {
    }

    public CellId(int id, int cardId) {
       this.id = id;
       this.cardId = cardId;
    }
   

    @Column(name="id", nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    @Column(name="card_id", nullable=false)
    public int getCardId() {
        return this.cardId;
    }
    
    public void setCardId(int cardId) {
        this.cardId = cardId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CellId) ) return false;
		 CellId castOther = ( CellId ) other; 
         
		 return (this.getId()==castOther.getId())
 && (this.getCardId()==castOther.getCardId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getId();
         result = 37 * result + this.getCardId();
         return result;
   }   


}


