package ru.terra.activitystore.db.entity;
// Generated 05.07.2012 13:20:05 by Hibernate Tools 3.2.1.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ListVal generated by hbm2java
 */
@Entity
@Table(name="list_val"
    ,catalog="activitystore"
)
public class ListVal  implements java.io.Serializable {


     private ListValId id;
     private Vlist vlist;
     private String value;

    public ListVal() {
    }

    public ListVal(ListValId id, Vlist vlist, String value) {
       this.id = id;
       this.vlist = vlist;
       this.value = value;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="valId", column=@Column(name="val_id", nullable=false) ), 
        @AttributeOverride(name="listId", column=@Column(name="list_id", nullable=false) ) } )
    public ListValId getId() {
        return this.id;
    }
    
    public void setId(ListValId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="list_id", nullable=false, insertable=false, updatable=false)
    public Vlist getVlist() {
        return this.vlist;
    }
    
    public void setVlist(Vlist vlist) {
        this.vlist = vlist;
    }
    
    @Column(name="value", nullable=false, length=500)
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }




}


