package ru.terra.activitystore.db.entity;
// Generated 05.07.2012 13:20:05 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ListValId generated by hbm2java
 */
@Embeddable
public class ListValId  implements java.io.Serializable {


     private int valId;
     private int listId;

    public ListValId() {
    }

    public ListValId(int valId, int listId) {
       this.valId = valId;
       this.listId = listId;
    }
   

    @Column(name="val_id", nullable=false)
    public int getValId() {
        return this.valId;
    }
    
    public void setValId(int valId) {
        this.valId = valId;
    }

    @Column(name="list_id", nullable=false)
    public int getListId() {
        return this.listId;
    }
    
    public void setListId(int listId) {
        this.listId = listId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ListValId) ) return false;
		 ListValId castOther = ( ListValId ) other; 
         
		 return (this.getValId()==castOther.getValId())
 && (this.getListId()==castOther.getListId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getValId();
         result = 37 * result + this.getListId();
         return result;
   }   


}


