package ru.terra.activitystore.db.entity;
// Generated 05.07.2012 13:20:05 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TemplateId generated by hbm2java
 */
@Embeddable
public class TemplateId  implements java.io.Serializable {


     private int id;
     private int card;

    public TemplateId() {
    }

    public TemplateId(int id, int card) {
       this.id = id;
       this.card = card;
    }
   

    @Column(name="id", nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    @Column(name="card", nullable=false)
    public int getCard() {
        return this.card;
    }
    
    public void setCard(int card) {
        this.card = card;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TemplateId) ) return false;
		 TemplateId castOther = ( TemplateId ) other; 
         
		 return (this.getId()==castOther.getId())
 && (this.getCard()==castOther.getCard());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getId();
         result = 37 * result + this.getCard();
         return result;
   }   


}


